import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";
import { Product } from "@/types/product";
import { getAllProducts } from "@/lib/api";
import "./globals.css"; // ✅ behåll denna

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const products: Product[] = await getAllProducts();

  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${cormorant.variable} antialiased text-neutral-950`}
      >
        <CartProvider>
          <Navbar products={products} />
          <div>{children}</div>
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
